// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: arith.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Args 示例请求, 与 api.Args 对应
type Args struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	A             int64                  `protobuf:"varint,1,opt,name=a,proto3" json:"a,omitempty"`
	B             int64                  `protobuf:"varint,2,opt,name=b,proto3" json:"b,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Args) Reset() {
	*x = Args{}
	mi := &file_arith_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Args) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Args) ProtoMessage() {}

func (x *Args) ProtoReflect() protoreflect.Message {
	mi := &file_arith_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Args.ProtoReflect.Descriptor instead.
func (*Args) Descriptor() ([]byte, []int) {
	return file_arith_proto_rawDescGZIP(), []int{0}
}

func (x *Args) GetA() int64 {
	if x != nil {
		return x.A
	}
	return 0
}

func (x *Args) GetB() int64 {
	if x != nil {
		return x.B
	}
	return 0
}

// Reply 示例响应, 与 api.Reply 对应
type Reply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        int64                  `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Reply) Reset() {
	*x = Reply{}
	mi := &file_arith_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Reply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Reply) ProtoMessage() {}

func (x *Reply) ProtoReflect() protoreflect.Message {
	mi := &file_arith_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Reply.ProtoReflect.Descriptor instead.
func (*Reply) Descriptor() ([]byte, []int) {
	return file_arith_proto_rawDescGZIP(), []int{1}
}

func (x *Reply) GetResult() int64 {
	if x != nil {
		return x.Result
	}
	return 0
}

// Big 用于对比大包场景下两种编码的开销差异
type Big struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []int64                `protobuf:"varint,1,rep,packed,name=values,proto3" json:"values,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Big) Reset() {
	*x = Big{}
	mi := &file_arith_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Big) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Big) ProtoMessage() {}

func (x *Big) ProtoReflect() protoreflect.Message {
	mi := &file_arith_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Big.ProtoReflect.Descriptor instead.
func (*Big) Descriptor() ([]byte, []int) {
	return file_arith_proto_rawDescGZIP(), []int{2}
}

func (x *Big) GetValues() []int64 {
	if x != nil {
		return x.Values
	}
	return nil
}

func (x *Big) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

var File_arith_proto protoreflect.FileDescriptor

const file_arith_proto_rawDesc = "" +
	"\n" +
	"\varith.proto\x12\x03api\"\"\n" +
	"\x04Args\x12\f\n" +
	"\x01a\x18\x01 \x01(\x03R\x01a\x12\f\n" +
	"\x01b\x18\x02 \x01(\x03R\x01b\"\x1f\n" +
	"\x05Reply\x12\x16\n" +
	"\x06result\x18\x01 \x01(\x03R\x06result\"1\n" +
	"\x03Big\x12\x16\n" +
	"\x06values\x18\x01 \x03(\x03R\x06values\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04textB\x14Z\x12kamaRPC/pkg/api/pbb\x06proto3"

var (
	file_arith_proto_rawDescOnce sync.Once
	file_arith_proto_rawDescData []byte
)

func file_arith_proto_rawDescGZIP() []byte {
	file_arith_proto_rawDescOnce.Do(func() {
		file_arith_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_arith_proto_rawDesc), len(file_arith_proto_rawDesc)))
	})
	return file_arith_proto_rawDescData
}

var file_arith_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_arith_proto_goTypes = []any{
	(*Args)(nil),  // 0: api.Args
	(*Reply)(nil), // 1: api.Reply
	(*Big)(nil),   // 2: api.Big
}
var file_arith_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_arith_proto_init() }
func file_arith_proto_init() {
	if File_arith_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_arith_proto_rawDesc), len(file_arith_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_arith_proto_goTypes,
		DependencyIndexes: file_arith_proto_depIdxs,
		MessageInfos:      file_arith_proto_msgTypes,
	}.Build()
	File_arith_proto = out.File
	file_arith_proto_goTypes = nil
	file_arith_proto_depIdxs = nil
}
